// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlertKind } from "./AlertKind";

/**
 * A notification the shell should surface (sound / toast / taskbar flash).
 */
export type Alert = { key: number | null, kind: AlertKind, title: string, body: string, sound: boolean, toast: boolean, flash: boolean, };
