// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostConfig } from "./HostConfig";
import type { LabelDef } from "./LabelDef";
import type { SoundPrefs } from "./SoundPrefs";
import type { UiPrefs } from "./UiPrefs";

export type AppConfig = { hosts: Array<HostConfig>, sound: SoundPrefs, 
/**
 * Label definitions; panes reference them by `id` (stored in tmux as `@chm_labels`).
 */
labels: Array<LabelDef>, ui: UiPrefs, };
