// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostConfig } from "./HostConfig";
import type { SoundPrefs } from "./SoundPrefs";

export type AppConfig = { hosts: Array<HostConfig>, sound: SoundPrefs, };
