// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthMode = { "kind": "auto" } | { "kind": "agent" } | { "kind": "keyFile", path: string, };
