// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppConfig } from "./AppConfig";
import type { HostState } from "./HostState";
import type { PaneAttention } from "./PaneAttention";
import type { PaneInfo } from "./PaneInfo";
import type { TailnetStatus } from "./TailnetStatus";

export type CoreSnapshot = { tailnet: TailnetStatus, config: AppConfig, hosts: Array<HostState>, panes: Array<PaneInfo>, attention: Array<PaneAttention>, };
