// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppConfig } from "./AppConfig";
import type { HostState } from "./HostState";
import type { NoticeLevel } from "./NoticeLevel";
import type { PaneAttention } from "./PaneAttention";
import type { PaneInfo } from "./PaneInfo";
import type { TailnetStatus } from "./TailnetStatus";

/**
 * Everything pushed to the UI (JSON). High-volume pane content goes through binary frames.
 */
export type CoreEvent = { "type": "tailnet", status: TailnetStatus, } | { "type": "config", config: AppConfig, } | { "type": "host", state: HostState, } | { "type": "hostRemoved", id: string, } | { "type": "panes", host: string, panes: Array<PaneInfo>, } | { "type": "attention", state: PaneAttention, } | { "type": "notice", host: string | null, level: NoticeLevel, message: string, } | { "type": "clipboard", key: number, text: string, };
