// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DirEntryInfo = { name: string, 
/**
 * A directory (or a symlink to one).
 */
isDir: boolean, isSymlink: boolean, size: number, 
/**
 * Modification time, unix seconds.
 */
mtime: number, };
