// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirEntryInfo } from "./DirEntryInfo";

export type DirListing = { 
/**
 * Canonical absolute path.
 */
path: string, home: string, entries: Array<DirEntryInfo>, };
