// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DriveKind } from "./DriveKind";

/**
 * A drive on this machine (Windows), for the explorer's drive buttons.
 */
export type DriveInfo = { 
/**
 * Its root, `D:/` (never `D:`, which means "the current folder on D:").
 */
path: string, 
/**
 * `D:`
 */
label: string, kind: DriveKind, 
/**
 * The volume label of a fixed drive ("New Volume"), if it has one.
 */
volume: string | null, };
