// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a file looked like when read or written, to notice changes made by someone else.
 */
export type FileStamp = { size: number, 
/**
 * Unix seconds.
 */
mtime: number, 
/**
 * FNV-1a of the bytes, for files up to [`HASH_LIMIT`].
 */
hash: string | null, };
