// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileStamp } from "./FileStamp";

/**
 * A file opened for editing.
 */
export type FileContent = { "kind": "text", text: string, bom: boolean, stamp: FileStamp, } | { "kind": "binary", stamp: FileStamp, } | { "kind": "tooLarge", stamp: FileStamp, };
