// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the user is looking at.
 */
export type FocusState = { expanded: number | null, windowFocused: boolean, };
