// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A change to the file system, requested by the explorer.
 */
export type FsOp = { "kind": "mkdir", path: string, } | { "kind": "createFile", path: string, } | { "kind": "rename", from: string, to: string, } | { "kind": "remove", path: string, };
