// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitFileStatus } from "./GitFileStatus";

export type GitEntry = { 
/**
 * Relative to the repository root, `/`-separated; ignored directories end with `/`.
 */
path: string, status: GitFileStatus, };
