// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitEntry } from "./GitEntry";

export type GitStatus = { 
/**
 * Absolute repository root (forward slashes).
 */
root: string, branch: string | null, entries: Array<GitEntry>, };
