// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file's committed version, for the editor's change gutter.
 */
export type HeadVersion = { "kind": "notInRepo" } | { "kind": "untracked" } | { "kind": "text", text: string, } | { "kind": "skipped" };
