// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostErrorKind } from "./HostErrorKind";

export type HostPhase = { "phase": "disconnected" } | { "phase": "connecting" } | { "phase": "awaitingTailscaleCheck", url: string, } | { "phase": "connected" } | { "phase": "reconnecting", attempt: number, retryInMs: number, lastError: string, } | { "phase": "failed", error: string, kind: HostErrorKind, };
