// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMode } from "./AuthMode";

export type HostConfig = { id: string, 
/**
 * Address to dial. When absent, the tailnet IP from `tailscale status` is used.
 */
address: string | null, port: number, user: string, auth: AuthMode, 
/**
 * Connect automatically on launch and keep reconnecting.
 */
autoConnect: boolean, };
