// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Facts learned about a host after connecting.
 */
export type HostFacts = { user: string, home: string, shell: string, uname: string, 
/**
 * e.g. "3.4"; `None` if tmux isn't installed.
 */
tmuxVersion: string | null, 
/**
 * Where tmux is, when the login shell's PATH doesn't have it.
 */
tmuxPath: string | null, };
