// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostFacts } from "./HostFacts";
import type { HostPhase } from "./HostPhase";

/**
 * Runtime state of a configured host.
 */
export type HostState = { id: string, phase: HostPhase, facts: HostFacts | null, };
