// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolStatus } from "./ToolStatus";

export type IntegrationStatus = { claude: ToolStatus, codex: ToolStatus, omp: ToolStatus, 
/**
 * Human-readable notes (what was changed, backups, caveats).
 */
notes: Array<string>, };
