// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user-defined pane label ("tag"). The id is a slug fixed at creation, so renaming a label
 * never needs to rewrite options on (possibly offline) hosts.
 */
export type LabelDef = { id: string, name: string, 
/**
 * CSS colour, e.g. `#f5a25d`.
 */
color: string, };
