// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A shell the user can start on this machine.
 */
export type LocalShell = { id: string, name: string, path: string, };
