// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Harness } from "./Harness";

/**
 * Request to create a new pane (and usually a new tmux session) running a harness.
 */
export type NewPaneSpec = { host: string, 
/**
 * Absolute working directory on the host.
 */
cwd: string, harness: Harness, 
/**
 * Window (and default session) name; derived from the directory when absent.
 */
name: string | null, 
/**
 * Add a window to this existing session instead of creating a new one.
 */
session: string | null, 
/**
 * Extra command-line arguments for the harness.
 */
args: string | null, 
/**
 * A plain shell on its own PTY instead of a tmux pane (lost on disconnect).
 */
direct?: boolean, 
/**
 * Local shells: which one (a [`LocalShell`] id). Remote direct shells use the login shell.
 */
shell?: string, };
