// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Harness } from "./Harness";
import type { PaneKind } from "./PaneKind";
import type { TmuxLoc } from "./TmuxLoc";

/**
 * One pane, as shown in the grid.
 */
export type PaneInfo = { 
/**
 * App-wide numeric key; frames for this pane carry it.
 */
key: number, host: string, kind: PaneKind, 
/**
 * Set for [`PaneKind::Tmux`] panes.
 */
tmux: TmuxLoc | null, width: number, height: number, currentCommand: string, currentPath: string, title: string, harness: Harness | null, alternateOn: boolean, 
/**
 * Stable identity: set on panes the app created (and on tmux panes the user has
 * expanded), used to key per-pane preferences.
 */
chmId: string | null, hidden: boolean, 
/**
 * Label ids (see [`LabelDef`]).
 */
labels: Array<string>, 
/**
 * Direct panes: why the session ended. The pane stays readable until dismissed.
 */
ended: string | null, 
/**
 * The user's choice to ping (or not) when this pane rings the terminal bell.
 */
bell: boolean | null, 
/**
 * Whether a bell pings: the user's choice, else on for chat clients (irssi, weechat, …).
 */
bellPings: boolean, };
