// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Activity } from "./Activity";
import type { AttentionLevel } from "./AttentionLevel";

export type PaneAttention = { key: number, activity: Activity, attention: AttentionLevel, 
/**
 * Short human description, e.g. "Finished", "Needs permission: Bash".
 */
reason: string | null, 
/**
 * Unix seconds of the last state change.
 */
since: number, 
/**
 * Increments on transient events (a subagent finished) so the UI can pulse the tile.
 */
pulse: number, 
/**
 * "hook" (reported by the harness) or "heuristic" (guessed from output activity).
 */
source: string, };
