// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Harness } from "./Harness";

/**
 * One tmux pane, as shown in the grid.
 */
export type PaneInfo = { 
/**
 * App-wide numeric key; frames for this pane carry it.
 */
key: number, host: string, 
/**
 * tmux ids, e.g. `%3`, `@2`, `$1`.
 */
paneId: string, windowId: string, sessionId: string, sessionName: string, sessionGroup: string | null, windowIndex: number, windowName: string, paneIndex: number, width: number, height: number, currentCommand: string, currentPath: string, title: string, harness: Harness | null, dead: boolean, alternateOn: boolean, windowActive: boolean, paneActive: boolean, 
/**
 * Set on panes the app created (and on panes the user has expanded, for stable identity).
 */
chmId: string | null, hidden: boolean, 
/**
 * Panes in this pane's tmux window (resizing a split window affects its neighbours).
 */
windowPanes: number, 
/**
 * Harness Manager has pinned this window's size.
 */
sized: boolean, 
/**
 * Label ids (see [`LabelDef`]).
 */
labels: Array<string>, };
