// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a resize request.
 */
export type ResizeOutcome = { 
/**
 * Regular (non-control) tmux clients also showing this pane's session, e.g. a phone.
 * Their view of a pinned window is cropped or padded.
 */
otherClients: number, };
