// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileStamp } from "./FileStamp";

/**
 * Why a save didn't happen.
 */
export type SaveError = { "kind": "conflict", current: FileStamp | null, } | { "kind": "failed", message: string, };
