// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Notification sound preferences.
 */
export type SoundPrefs = { 
/**
 * Master switch for chimes.
 */
enabled: boolean, 
/**
 * 0.0 – 1.0.
 */
volume: number, finished: boolean, needsInput: boolean, subtask: boolean, bell: boolean, 
/**
 * Windows toasts when the app isn't focused.
 */
toasts: boolean, };
