// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TailnetPeer } from "./TailnetPeer";

export type TailnetStatus = { 
/**
 * Tailscale's BackendState: NoState, NeedsLogin, NeedsMachineAuth, Stopped, Starting, Running.
 */
backendState: string, 
/**
 * Login URL when Tailscale needs the user to authenticate.
 */
authUrl: string | null, selfNode: TailnetPeer | null, peers: Array<TailnetPeer>, tailnetName: string | null, health: Array<string>, 
/**
 * Set when the Tailscale CLI couldn't be run or its output couldn't be parsed.
 */
error: string | null, };
