// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TailnetPeer = { 
/**
 * Short name derived from the MagicDNS name; used as the [`HostId`].
 */
id: string, hostName: string, dnsName: string, os: string, ips: Array<string>, online: boolean, 
/**
 * OpenSSH-format public host keys advertised by Tailscale (used for pinning).
 */
sshHostKeys: Array<string>, isSelf: boolean, };
