// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a tmux pane lives.
 */
export type TmuxLoc = { 
/**
 * tmux ids, e.g. `%3`, `@2`, `$1`.
 */
paneId: string, windowId: string, sessionId: string, sessionName: string, sessionGroup: string | null, windowIndex: number, windowName: string, paneIndex: number, dead: boolean, windowActive: boolean, paneActive: boolean, 
/**
 * Panes in this pane's tmux window (resizing a split window affects its neighbours).
 */
windowPanes: number, 
/**
 * Harness Manager has pinned this window's size.
 */
sized: boolean, 
/**
 * The server's prefix key as tmux names it (`C-b` unless the user changed it).
 */
prefix: string, };
