// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * tmux's own window operations, aimed at a pane (prefix keys in the expanded view).
 */
export type TmuxOp = { "kind": "newWindow" } | { "kind": "split", horizontal: boolean, } | { "kind": "renameWindow", name: string, } | { "kind": "renameSession", name: string, };
