// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * UI preferences that must survive anything (a quit, a crash, a wiped WebView profile), so
 * the core keeps them in `config.json` instead of the webview's storage.
 */
export type UiPrefs = { 
/**
 * Machine id → the folder the Files explorer and the new-pane dialog start in.
 */
defaultFolders: { [key in string]: string }, 
/**
 * Recording mode: personal details are masked everywhere, toasts name nothing.
 */
recording: boolean, 
/**
 * …machine names too.
 */
hideMachineNames: boolean, };
